#!/bin/bash

while true; do
    echo "      NGINX MANAGEMENT TOOL"
    echo "1) Install Nginx"
    echo "2) Uninstall Nginx"
    echo "3) Start/Stop/Restart Nginx"
    echo "4) Check Service Status"
    echo "5) Exit"
    read -p "What would you like to do? [1-6]: " choice

    case $choice in
        1)
            sudo apt update && sudo apt install nginx -y
            sudo ufw allow 'Nginx Full'
            echo "Nginx installed."
            ;;
        2)
            read -p "Are you sure? (y/n): " confirm
            if [[ $confirm == "y" ]]; then
                sudo apt purge nginx nginx-common -y && sudo apt autoremove -y
                echo "Nginx uninstalled."
            fi
            ;;
        3)
            echo "a) Start  b) Stop  c) Restart"
            read -p "Action: " action
            [[ $action == "a" ]] && sudo systemctl start nginx
            [[ $action == "b" ]] && sudo systemctl stop nginx
            [[ $action == "c" ]] && sudo systemctl restart nginx
            ;;
        4)
            systemctl status nginx --no-pager
            ;;

        5)
            echo "Exiting."
            exit 0
            ;;
        *)
            echo "Invalid option."
            ;;
    esac
    echo ""
done