#SPDX-License-Identifier: MIT-0
---
# handlers file for nginx
# MAIN.YML HANDLER
- name: Restart nginx
  service:
    name: nginx
    state: restarted
 
- name: Reload nginx
  service:
    name: nginx
    state: reloaded