- name: Provision AWS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create a Security group
      amazon.aws.ec2_group:
        name: "Aws_infra_ansible3-sg"
        description: "Allow HTTP, SSH, TOMCAT ports"
        region: "us-east-1"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 3306
            to_port: 3306
            cidr_ip: 0.0.0.0/0

    - name: Launch/Start the instance
      amazon.aws.ec2_instance:
        name: "Aws_infra_ansible3"
        key_name: "master-key-pair"
        instance_type: "t3.micro"
        image_id: "ami-0c7217cdde317cfec"
        security_groups: ["Aws_infra_ansible3-sg"]
        region: "us-east-1"
        wait: yes
      register: ec2_result

    - name: Save the new IP
      add_host:
        hostname: "{{ ec2_result.instances[0].public_ip_address }}"
        groupname: new_servers