#SPDX-License-Identifier: MIT-0
---
# tasks file for system_manager

- name: Install Packages
  include_tasks: packages.yml

- name: Create Users
  include_tasks: users.yml

- name: Set up Folders
  include_tasks: folders.yml

- name: Manage Git repo
  include_tasks: git.yml