---
- name: Ensure the sudo group exists
  group:
    name: sudo
    state: present

- name: Ensure the user exist here
  user: 
    name: "{{ item.name }}"
    group: "{{ item.group | default('') }}"
    shell: "{{ item.shell | default('/bin/sh')}}"
    state: present
  loop: "{{ system_users }}"