#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx_v2

- name: Load OS-specific variables
  include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Install Nginx
  package: 
    name: "{{ nginx_package }}"
    state: "{{ nginx_version }}"  

- name: Deploy Nginx configuration from template
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes